### ISSUE TITLE
作業 1 的回覆

### ISSUE THREAD

**Issue by azole** [bscny/git-practice#1]
1. readme.md

> - 不要學完之後就忘掉，加減複習
> - 盡可能跟上吸收所有知識

這門課只期許自己做到這兩點可能不夠，這門課會需要你們先預習＋大量的動手實作跟驗證，這兩個動作也是讓你真正吸收知識的關鍵，真正吸收後，也比較不會忘掉，甚至忘掉細節又有什麼關係？能趕快動手實證就好？

2. video.md
對，影片中的東西都是老生常談，除了尋求幫助跟多學習外，你還會做什麼「具體」的動作，例如你會怎麼多學習？

3. git.md
你有附上出處很好，但不能只有出處，我想看到你自己消化吸收後的結論，那才是你自己的東西。或者是，你怎麼確認這篇文章講的是對的？你有實際動手觀察過 .git 檔案夾內的什麼變化來驗證某一個知識點嗎？有的話，請補充上來給我，沒有的話，那這份作業是不算合格的。  --> 動手實證文章中提到的知識點，這是我能給你的「多學習、不去死記」的一個建議。

**Comment by bscny** [comment]
老師好

已做出修改

游宗諺 上

azole ***@***.***> 於 2024年9月14日 週六 上午10:52寫道：

**Comment by azole** [comment]
宗諺，謝謝你的補充與回覆，記得要去看一下課堂上分享的、這次做得不錯的作業，幫自己訂一個更高一點的標準來努力，期待你之後的作業，加油。

如果沒有其他要跟我討論的部分，這個 issue 就可以先 close 了。
